- id: '1549872178100'
  alias: 'Hue Tap Uno #2'
  trigger:
  - event_data:
      event: 16
      id: hue_tap_uno
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - data:
      entity_id: light.stue_vegg_level
    service: light.turn_on
- id: '1549907898507'
  alias: 'Hue Tap Uno #1'
  trigger:
  - event_data:
      event: 34
      id: hue_tap_uno
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - data:
      entity_id: light.stue_vegg_level
    service: light.turn_off
- id: '1550001835411'
  alias: 'The Button #1, 1 click'
  trigger:
  - event_data:
      entity_id: zwave.fibaro_button_1
      scene_data: 7680
      scene_id: 1
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - data:
      entity_id: switch.gang_oppe_switch
    service: switch.toggle
- id: '1550606425406'
  alias: Keyfob Car, Square Hold
  trigger:
  - event_data:
      entity_id: zwave.fibaro_keyfob_carkey
      scene_data: 7680
      scene_id: 1
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - data:
      entity_id: switch.garasjeport
    service: switch.turn_on
- id: '1551629601000'
  alias: Keyfob Car, Cross Hold
  trigger:
  - event_data:
      entity_id: zwave.fibaro_keyfob_carkey
      scene_data: 7680
      scene_id: 3
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - data:
      entity_id: lock.hoveddor
      code: !secret verisure_pin
    service: lock.unlock
- id: '1551651260765'
  alias: Motion Gang
  trigger:
  - entity_id: sensor.gang_motion
    from: '0'
    platform: state
    to: '8'
  condition:
  - condition: state
    entity_id: switch.yttergang
    state: 'off'
  action:
  - data:
      entity_id: scene.gang_pa
    service: scene.turn_on
