- id: '155821217700'
  alias: Kjeller Bod Enter
  trigger:
  - entity_id: binary_sensor.kjeller_bod_sensor_home_security_motion_detection
    platform: state
    to: 'on'
    from: 'off'
  action:
  - data:
      entity_id: scene.kjeller_bod_pa
    service: scene.turn_on
- id: '155821217701'
  alias: Kjeller Bod Exit
  trigger:
  - entity_id: binary_sensor.kjeller_bod_sensor_home_security_motion_detection
    for: 00:15
    platform: state
    from: 'on'
    to: 'off'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: binary_sensor.octoprint_printing
      state: 'off'
    - condition: state
      entity_id: binary_sensor.octoprint_printing
      state: unavailable
  action:
  - data:
      entity_id: scene.kjeller_bod_av
    service: scene.turn_on
  mode: single
- id: '1551651260765'
  alias: Motion Gang
  trigger:
  - entity_id: binary_sensor.gang_sensor_home_security_motion_detection
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: switch.yttergang
    state: 'off'
  - after: 06:00:00
    before: '21:00:00'
    condition: time
  action:
  - data:
      entity_id: scene.gang_pa
    service: scene.turn_on
  mode: single
- id: '1572437961272'
  alias: Varme, Lav når borte eller kveld
  description: ''
  trigger:
  - at: '22:00'
    platform: time
  - entity_id: group.all_persons
    for: 00:30
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - service: script.lav_varme
- id: '1572438496325'
  alias: Varme, Høy når hjemme
  description: ''
  trigger:
  - entity_id: group.all_persons
    from: not_home
    platform: state
    to: home
  condition:
  - before: '22:00:00'
    condition: time
    after: 06:00:00
  action:
  - service: script.hoy_varme
- id: '1572894057692'
  alias: Varme, Høy på morgen i helg
  description: ''
  trigger:
  - at: 08:00
    platform: time
  condition:
  - condition: state
    entity_id: group.all_persons
    state: home
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'off'
  action:
  - service: script.hoy_varme
- id: '1583994012421'
  alias: Varme, Høy på morgen ukedager
  description: ''
  trigger:
  - at: 06:00
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  - condition: state
    entity_id: group.all_persons
    state: home
  action:
  - data: {}
    service: script.hoy_varme
- id: '1586514634514'
  alias: Lås dører når ingen hjemme
  description: ''
  trigger:
  - entity_id: group.all_persons
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - data: {}
    service: lock.lock
    target:
      entity_id:
      - lock.boddor
      - lock.hoveddor
- id: '1587456032987'
  alias: Garderobelys Svakt
  description: ''
  trigger:
  - entity_id: light.soverom_seng
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      brightness: 12
      transition: 3
    entity_id:
    - light.garderobe_stine
    - light.garderobe_torkild
    service: light.turn_on
- id: '1587456195101'
  alias: Garderobelys Kraftig
  description: ''
  trigger:
  - entity_id: light.soverom_seng
    from: 'off'
    platform: state
  condition: []
  action:
  - data:
      brightness: 255
      transition: 3
    entity_id:
    - light.garderobe_stine
    - light.garderobe_torkild
    service: light.turn_on
  mode: single
- id: '1600502553956'
  alias: Tag Hoveddør is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 749bf980-aed0-476c-8156-ae3e53dbb8aa
  condition: []
  action:
  - service: lock.unlock
    data: {}
    entity_id: lock.hoveddor
  mode: single
- id: '1607377536167'
  alias: Octoprint Start
  description: ''
  trigger:
  - entity_id: binary_sensor.octoprint_printing
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: scene.kjeller_bod_pa
    service: scene.turn_on
  mode: single
- id: '1617095260219'
  alias: Plantelampe På
  description: ''
  trigger:
  - platform: time
    at: 08:00:00
  condition: []
  action:
  - type: turn_on
    device_id: 36a9aa044d32f7e0481e7511bf4d6449
    entity_id: switch.plantelampe
    domain: switch
  mode: single
- id: '1617095288500'
  alias: Plantelampe Av
  description: ''
  trigger:
  - platform: time
    at: '20:00:00'
  condition: []
  action:
  - type: turn_off
    device_id: 36a9aa044d32f7e0481e7511bf4d6449
    entity_id: switch.plantelampe
    domain: switch
  mode: single
- id: '1625740809871'
  alias: Garasjelys på
  description: ''
  trigger:
  - platform: device
    device_id: 48be7c045b27f5f27f6e40300f660060
    domain: cover
    entity_id: cover.garage_door
    type: opening
  - platform: device
    device_id: 48be7c045b27f5f27f6e40300f660060
    domain: cover
    entity_id: cover.garage_door
    type: opened
  - type: opened
    platform: device
    device_id: ed86bed515f26038b50d25f88e0725a5
    entity_id: binary_sensor.garasjeport_in2
    domain: binary_sensor
  condition: []
  action:
  - service: light.turn_on
    target:
      entity_id: light.garasjelys
  mode: single
- id: '1625740885485'
  alias: Garasjelys av
  description: ''
  trigger:
  - platform: device
    device_id: 48be7c045b27f5f27f6e40300f660060
    domain: cover
    entity_id: cover.garage_door
    type: closed
  - type: not_opened
    platform: device
    device_id: ed86bed515f26038b50d25f88e0725a5
    entity_id: binary_sensor.garasjeport_in2
    domain: binary_sensor
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id: light.garasjelys
  mode: single
- id: '1635085004822'
  alias: Julelys på ved solnedgang
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - type: turn_on
    device_id: b025f501dc90b4173f927b5220719695
    entity_id: switch.popp_smart_outdoor_plug_ip44_rated
    domain: switch
  mode: single
- id: '1635085028962'
  alias: Julelys av ved soloppgang
  description: ''
  trigger:
  - platform: sun
    event: sunrise
  condition: []
  action:
  - type: turn_off
    device_id: b025f501dc90b4173f927b5220719695
    entity_id: switch.popp_smart_outdoor_plug_ip44_rated
    domain: switch
  mode: single
- id: '1638961078194'
  alias: UniFi Protect Doorbell Notifications
  description: ''
  use_blueprint:
    path: briis/push_notification_doorbell_event.yaml
    input:
      doorbell: binary_sensor.doorbell_doorbell
      lock_entity: lock.hoveddor
      time_format: '%H:%M'
      base_ha_url: https://pz7cv2ag25qss8qgtihrgix7y08kr07d.ui.nabu.casa
      base_image_url: https://pz7cv2ag25qss8qgtihrgix7y08kr07d.ui.nabu.casa
      lovelace_view: /lovelace/door
      tts_target: cloud_say
      lock_tts: Døren blir nå låst opp
- id: '1664892858557'
  alias: Prusa Mini Idle
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.prusamini
    for:
      hours: 1
      minutes: 0
      seconds: 0
    from: printing
  - platform: state
    entity_id:
    - sensor.octoprint_current_state
    from: Printing
    for:
      hours: 1
      minutes: 0
      seconds: 0
  condition:
  - condition: not
    conditions:
    - condition: or
      conditions:
      - condition: state
        entity_id: sensor.octoprint_current_state
        state: Printing
      - condition: state
        entity_id: sensor.prusamini
        state: printing
  action:
  - service: switch.turn_off
    data: {}
    target:
      device_id: 455aa6d98d3d51d313c2c555afa11682
  mode: single
- id: '1666426398324'
  alias: Varmepumpe bytt til vifte når varmt
  description: ''
  trigger:
  - platform: device
    device_id: edf1f4de0fa0fdfcfdf0437d82b329a8
    domain: climate
    entity_id: climate.stue
    type: current_temperature_changed
    above: 24
  condition:
  - condition: device
    device_id: 7d6a1331d797e1b09dbcf705e11ecf34
    domain: climate
    entity_id: climate.varmepumpe
    type: is_hvac_mode
    hvac_mode: heat
  action:
  - service: climate.set_hvac_mode
    data:
      hvac_mode: fan_only
    target:
      device_id: 7d6a1331d797e1b09dbcf705e11ecf34
  - service: climate.set_fan_mode
    data:
      fan_mode: '4'
    target:
      device_id: 7d6a1331d797e1b09dbcf705e11ecf34
  mode: single
- id: '1666426636912'
  alias: Varmepumpe bytt til varme når kaldere
  description: ''
  trigger:
  - platform: device
    device_id: edf1f4de0fa0fdfcfdf0437d82b329a8
    domain: climate
    entity_id: climate.stue
    type: current_temperature_changed
    below: 23
  condition:
  - condition: device
    device_id: 7d6a1331d797e1b09dbcf705e11ecf34
    domain: climate
    entity_id: climate.varmepumpe
    type: is_hvac_mode
    hvac_mode: fan_only
  action:
  - service: climate.set_fan_mode
    data:
      fan_mode: auto
    target:
      device_id: 7d6a1331d797e1b09dbcf705e11ecf34
  - service: climate.set_hvac_mode
    data:
      hvac_mode: heat
    target:
      device_id: 7d6a1331d797e1b09dbcf705e11ecf34
  mode: single
