- id: '1549872178100'
  alias: 'Hue Tap Uno #2'
  trigger:
  - event_data:
      event: 16
      id: hue_tap_uno
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - data:
      entity_id: light.stue_vegg_level
    service: light.turn_on
- id: '1549907898507'
  alias: 'Hue Tap Uno #1'
  trigger:
  - event_data:
      event: 34
      id: hue_tap_uno
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - data:
      entity_id: light.stue_vegg_level
    service: light.turn_off
- id: '1550001835411'
  alias: 'The Button #1, 1 click'
  description: Gang
  trigger:
  - event_data:
      entity_id: zwave.fibaro_button_1
      scene_data: 7680
      scene_id: 1
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - data:
      entity_id: switch.garasjeport
    service: switch.turn_on
- id: '1550001835412'
  alias: 'The Button #1, 2 click'
  trigger:
  - event_data:
      entity_id: zwave.fibaro_button_1
      scene_data: 7860
      scene_id: 1
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - data:
      entity_id: lock.garasjeport
    service: lock.lock
- id: '1550606425406'
  alias: Keyfob Car, Square
  trigger:
  - event_data:
      entity_id: zwave.fibaro_keyfob_carkey
      scene_data: 7680
      scene_id: 1
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - data:
      entity_id: switch.garasjeport
    service: switch.turn_on
- id: '1551629601000'
  alias: Keyfob Car, Cross
  trigger:
  - event_data:
      entity_id: zwave.fibaro_keyfob_carkey
      scene_data: 7680
      scene_id: 3
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - data:
      entity_id: lock.hoveddor
    service: lock.unlock
- id: '155821217700'
  alias: Kjeller Bod Enter
  trigger:
  - entity_id: sensor.kjeller_bod_motion
    from: '0'
    platform: state
    to: '8'
  action:
  - data:
      entity_id: scene.kjeller_bod_pa
    service: scene.turn_on
- id: '155821217701'
  alias: Kjeller Bod Exit
  trigger:
  - entity_id: sensor.kjeller_bod_motion
    for: 00:15
    from: '8'
    platform: state
    to: '0'
  condition: []
  action:
  - data:
      entity_id: scene.kjeller_bod_av
    service: scene.turn_on
- id: '1551651260765'
  alias: Motion Gang
  trigger:
  - entity_id: sensor.gang_motion
    from: '0'
    platform: state
    to: '8'
  condition:
  - condition: state
    entity_id: switch.yttergang
    state: 'off'
  - after: 05:30:00
    before: '23:59:00'
    condition: time
  action:
  - data:
      entity_id: scene.gang_pa
    service: scene.turn_on
- id: '1554639006348'
  alias: 'The Button #2, 1 click'
  trigger:
  - event_data:
      entity_id: zwave.fibaro_button_2
      scene_data: 7680
      scene_id: 1
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - data:
      entity_id: lock.hoveddor
    service: lock.unlock
- id: '1556193117274'
  alias: Garasjeport Lenge Åpen
  trigger:
  - entity_id: binary_sensor.garasjeport
    for: 01:00:00
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Garasjeport har vært lenge åpen. Kanskje vurdere å lukke?
      title: Garasjeport åpen
    service: notify.web
- id: '1569079029593'
  alias: Garasjelys På
  trigger:
  - entity_id: binary_sensor.garasjeport
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: switch.garasjelys
    service: switch.turn_on
- id: '1569079029594'
  alias: Garasjelys Av
  trigger:
  - entity_id: binary_sensor.garasjeport
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: switch.garasjelys
    service: switch.turn_off
