- id: '155821217700'
  alias: Kjeller Bod Enter
  trigger:
  - entity_id: binary_sensor.kjeller_bod_sensor_home_security_motion_detection
    platform: state
    to: 'on'
    from: 'off'
  action:
  - data:
      entity_id: scene.kjeller_bod_pa
    service: scene.turn_on
- id: '155821217701'
  alias: Kjeller Bod Exit
  trigger:
  - entity_id: binary_sensor.kjeller_bod_sensor_home_security_motion_detection
    for: 00:15
    platform: state
    from: 'on'
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: scene.kjeller_bod_av
    service: scene.turn_on
  mode: single
- id: '1551651260765'
  alias: Motion Gang
  trigger:
  - entity_id: binary_sensor.gang_sensor_home_security_motion_detection
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: switch.yttergang
    state: 'off'
  - after: 06:00:00
    before: '21:00:00'
    condition: time
  action:
  - data:
      entity_id: scene.gang_pa
    service: scene.turn_on
  mode: single
- id: '1572437961272'
  alias: Varme, Lav når borte eller kveld
  description: ''
  trigger:
  - at: '22:00'
    platform: time
  - entity_id: group.all_persons
    for: 00:30
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - service: script.lav_varme
- id: '1572438496325'
  alias: Varme, Høy når hjemme
  description: ''
  trigger:
  - entity_id: group.all_persons
    from: not_home
    platform: state
    to: home
  condition:
  - before: '22:00:00'
    condition: time
    after: 06:00:00
  action:
  - service: script.hoy_varme
- id: '1572894057692'
  alias: Varme, Høy på morgen i helg
  description: ''
  trigger:
  - at: 08:00
    platform: time
  condition:
  - condition: state
    entity_id: group.all_persons
    state: home
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'off'
  action:
  - service: script.hoy_varme
- id: '1583994012421'
  alias: Varme, Høy på morgen ukedager
  description: ''
  trigger:
  - at: 06:00
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  - condition: state
    entity_id: group.all_persons
    state: home
  action:
  - data: {}
    service: script.hoy_varme
- id: '1586514634514'
  alias: Lås dører når ingen hjemme
  description: ''
  trigger:
  - entity_id: group.all_persons
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - data:
      code: '213943'
    service: lock.lock
    target:
      entity_id:
      - lock.boddor
      - lock.hoveddor
- id: '1587456032987'
  alias: Garderobelys Svakt
  description: ''
  trigger:
  - entity_id: light.soverom_seng
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      brightness: 12
      transition: 3
    entity_id:
    - light.garderobe_stine
    - light.garderobe_torkild
    service: light.turn_on
- id: '1587456195101'
  alias: Garderobelys Kraftig
  description: ''
  trigger:
  - entity_id: light.soverom_seng
    from: 'off'
    platform: state
  condition: []
  action:
  - data:
      brightness: 255
      transition: 3
    entity_id:
    - light.garderobe_stine
    - light.garderobe_torkild
    service: light.turn_on
  mode: single
- id: '1607377536167'
  alias: Prusa Mini - Start
  description: ''
  trigger:
  - entity_id: binary_sensor.octoprint_printing
    platform: state
    to: 'on'
  - platform: state
    entity_id:
    - sensor.prusamini
    to: printing
  condition: []
  action:
  - data:
      entity_id: scene.kjeller_bod_pa
    service: scene.turn_on
  mode: single
- id: '1617095260219'
  alias: Plantelampe På
  description: ''
  trigger:
  - platform: time
    at: 08:00:00
  condition: []
  action:
  - type: turn_on
    device_id: 36a9aa044d32f7e0481e7511bf4d6449
    entity_id: switch.plantelampe
    domain: switch
  mode: single
- id: '1617095288500'
  alias: Plantelampe Av
  description: ''
  trigger:
  - platform: time
    at: '20:00:00'
  condition: []
  action:
  - type: turn_off
    device_id: 36a9aa044d32f7e0481e7511bf4d6449
    entity_id: switch.plantelampe
    domain: switch
  mode: single
- id: '1625740809871'
  alias: Garasjelys på
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: ed86bed515f26038b50d25f88e0725a5
    entity_id: binary_sensor.garasjeport_in2
    domain: binary_sensor
  condition: []
  action:
  - service: light.turn_on
    target:
      entity_id: light.garasjelys
    data: {}
  mode: single
- id: '1625740885485'
  alias: Garasjelys av
  description: ''
  trigger:
  - type: not_opened
    platform: device
    device_id: ed86bed515f26038b50d25f88e0725a5
    entity_id: binary_sensor.garasjeport_in2
    domain: binary_sensor
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id: light.garasjelys
    data: {}
  mode: single
- id: '1635085004822'
  alias: Julelys på ved solnedgang
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - type: turn_on
    device_id: b025f501dc90b4173f927b5220719695
    entity_id: switch.popp_smart_outdoor_plug_ip44_rated
    domain: switch
  mode: single
- id: '1635085028962'
  alias: Julelys av ved soloppgang
  description: ''
  trigger:
  - platform: sun
    event: sunrise
  condition: []
  action:
  - type: turn_off
    device_id: b025f501dc90b4173f927b5220719695
    entity_id: switch.popp_smart_outdoor_plug_ip44_rated
    domain: switch
  mode: single
- id: '1664892858557'
  alias: Bambu Lab P1S - Idle
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.bambu_lab_p1s_current_stage
    for:
      hours: 1
      minutes: 0
      seconds: 0
    to: idle
  condition:
  - condition: state
    entity_id: sensor.bambu_lab_p1s_current_stage
    state: idle
  action:
  - service: switch.turn_off
    data: {}
    target:
      device_id: 455aa6d98d3d51d313c2c555afa11682
    enabled: false
  mode: single
- id: '1666426398324'
  alias: Varmepumpe bytt til vifte når varmt
  description: ''
  trigger:
  - platform: device
    device_id: edf1f4de0fa0fdfcfdf0437d82b329a8
    domain: climate
    entity_id: climate.stue
    type: current_temperature_changed
    above: 25
  condition:
  - condition: device
    device_id: 7d6a1331d797e1b09dbcf705e11ecf34
    domain: climate
    entity_id: climate.varmepumpe
    type: is_hvac_mode
    hvac_mode: heat
  action:
  - service: climate.set_hvac_mode
    data:
      hvac_mode: fan_only
    target:
      device_id: 7d6a1331d797e1b09dbcf705e11ecf34
  - service: climate.set_fan_mode
    data:
      fan_mode: '3'
    target:
      device_id: 7d6a1331d797e1b09dbcf705e11ecf34
  mode: single
- id: '1666426636912'
  alias: Varmepumpe bytt til varme når kaldere
  description: ''
  trigger:
  - platform: device
    device_id: edf1f4de0fa0fdfcfdf0437d82b329a8
    domain: climate
    entity_id: climate.stue
    type: current_temperature_changed
    below: 25
  condition:
  - condition: device
    device_id: 7d6a1331d797e1b09dbcf705e11ecf34
    domain: climate
    entity_id: climate.varmepumpe
    type: is_hvac_mode
    hvac_mode: fan_only
  action:
  - service: climate.set_fan_mode
    data:
      fan_mode: auto
    target:
      device_id: 7d6a1331d797e1b09dbcf705e11ecf34
  - service: climate.set_hvac_mode
    data:
      hvac_mode: heat
    target:
      device_id: 7d6a1331d797e1b09dbcf705e11ecf34
  mode: single
- id: '1683220669056'
  alias: Sykkellader av når inaktiv
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: 850e0240eb4a6a6806720efc2497176f
    entity_id: switch.sykkellader
    domain: switch
    for:
      hours: 4
      minutes: 0
      seconds: 0
  - type: power
    platform: device
    device_id: 850e0240eb4a6a6806720efc2497176f
    entity_id: sensor.sykkellader_electric_consumption_w
    domain: sensor
    below: 10
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition:
  - condition: device
    type: is_on
    device_id: 850e0240eb4a6a6806720efc2497176f
    entity_id: switch.sykkellader
    domain: switch
  action:
  - type: turn_off
    device_id: 850e0240eb4a6a6806720efc2497176f
    entity_id: switch.sykkellader
    domain: switch
  mode: single
- id: '1693335480646'
  alias: Kjeller Lekkasje
  description: ''
  trigger:
  - type: moist
    platform: device
    device_id: 0abda7781f5e5f2c99f7d6e8d4593897
    entity_id: e402d52658264ba395b18c6ebb45f35a
    domain: binary_sensor
  condition: []
  action:
  - service: notify.notify
    data:
      message: Vann oppdaget på gulv i kjellerboden!
      title: Lekkasje Kjeller!
  mode: single
- id: '1695122095265'
  alias: Garasjeport lenge åpen
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: ed86bed515f26038b50d25f88e0725a5
    entity_id: 3dfd4eb94848c1f898c57472bad26282
    domain: binary_sensor
    for:
      hours: 2
      minutes: 0
      seconds: 0
  condition: []
  action:
  - service: notify.notify
    data:
      message: 'Garasjeport har vært lenge åpen '
      title: Garasjeport åpen
  mode: single
- id: '1698525434241'
  alias: Fibaro Button 2
  description: ''
  use_blueprint:
    path: gsemet/zwave-js-fibaro-the-button-fgpb-101-v2021-12-08.yaml
    input:
      fibaro_thebutton: b59025eb73282788275f55402c520c36
      key_held_down: []
      key_pressed_1x:
      - service: media_player.play_media
        data:
          media_content_id: https://open.spotify.com/track/5F8c71PbayLIedqmjskrhM?si=030eed80309b4e7f
          media_content_type: music
        target:
          entity_id: media_player.livingroom
        alias: Badebussen
      key_pressed_2x:
      - service: media_player.play_media
        data:
          media_content_type: music
          media_content_id: https://open.spotify.com/track/5PTYydUwfxM8Q7KuqjmPxu?si=84130c9bc8564503
        target:
          device_id: 9be1d636ab984d40978892f5d7646ce5
        alias: BlimE! - Den Ene
      key_pressed_3x:
      - service: media_player.play_media
        data:
          media_content_id: https://open.spotify.com/track/4qfRVjN1pI0LrKRNxQ1JwQ?si=bb1d53380c004356
          media_content_type: music
        target:
          device_id: 9be1d636ab984d40978892f5d7646ce5
        alias: Brannbamsen Bjørnis
- id: '1699454114038'
  alias: Globus - Morgen
  description: ''
  trigger:
  - platform: time
    at: 05:30:00
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.brage_sol_ned_opp
    metadata: {}
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: scene.turn_on
    target:
      entity_id: scene.brage_sol_ned_opp
    metadata: {}
  mode: single
- id: '1699454210870'
  alias: Globus - Natt
  description: ''
  trigger:
  - platform: time
    at: '18:00:00'
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.brage_natt
    metadata: {}
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: scene.turn_on
    target:
      entity_id: scene.brage_natt
    metadata: {}
  mode: single
- id: '1699454243036'
  alias: Globus - Dag
  description: ''
  trigger:
  - platform: time
    at: 06:00:00
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.globus_dag
    metadata: {}
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: scene.turn_on
    target:
      entity_id: scene.globus_dag
    metadata: {}
  mode: single
- id: '1700912825579'
  alias: Prusa Mini - Prusa Link Idle
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.prusamini
    for:
      hours: 1
      minutes: 0
      seconds: 0
    from: printing
  condition:
  - condition: not
    conditions:
    - condition: state
      entity_id: sensor.prusamini
      state: printing
    alias: Is not printing
  action:
  - service: switch.turn_off
    data: {}
    target:
      device_id: 455aa6d98d3d51d313c2c555afa11682
    enabled: true
  mode: single
- id: '1701461491821'
  alias: Prusa Mini - Status Notification
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.prusamini_progress
  - platform: state
    entity_id:
    - sensor.prusamini
    from: printing
  condition:
  - alias: Is Available
    condition: not
    conditions:
    - condition: state
      entity_id: sensor.prusamini
      state: unavailable
  action:
  - service: notify.mobile_app_pixel_7
    data:
      title: "{% if is_state('sensor.prusamini', 'printing') %}\n  {{states('sensor.prusamini_filename')}}\n{%
        else %}\n  Prusa Mini\n{% endif %}"
      message: "{% if is_state('sensor.prusamini', 'printing') %}\n  {{ states('sensor.prusamini_progress')
        }}%, ETA: {{\n  (as_timestamp(states('sensor.prusamini_print_finish'))-as_timestamp(now()))
        | timestamp_custom('%H:%M', false)}} left.\n{% else %}\n  {{ states('sensor.prusamini')
        | title }}\n{% endif %}"
      data:
        channel: 3D Printer
        persistent: true
        sticky: true
        importance: medium
        tag: prusa-mini
        image: /api/camera_proxy/camera.octoprint
        clickAction: /lovelace/printer
    alias: Notify Status
  mode: single
- id: '1710182100943'
  alias: Screens - Åpne på kvelden
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 00:10:00
  condition: []
  action:
  - service: cover.open_cover
    metadata: {}
    data: {}
    target:
      device_id:
      - 75d8c4a9779dc4454e1983e8c098a2db
      - e0f6c68e77d712699591ff64bfa70850
  mode: single
- id: '1713685970398'
  alias: Screens - Lukke når mye lys
  description: ''
  trigger:
  - type: illuminance
    platform: device
    device_id: 2f5c8e67bac175a2c310ed3f12c7303c
    entity_id: 204300b43b083489f0a7bdaac174f11e
    domain: sensor
    above: 20000
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition:
  - condition: time
    after: '12:00:00'
    before: '20:00:00'
  action:
  - service: cover.close_cover
    metadata: {}
    data: {}
    target:
      device_id:
      - 75d8c4a9779dc4454e1983e8c098a2db
      - e0f6c68e77d712699591ff64bfa70850
  mode: single
- id: '1717057766861'
  alias: Bambu Lab P1S - Problem
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.bambu_lab_p1s_hms_errors
    to: 'on'
  condition: []
  action:
  - alias: Notify Status
    service: notify.mobile_app_pixel_7
    data:
      title: Bambu Lab P1S
      message: Printer needs your attention!
      data:
        channel: 3D Printer Attention
        persistent: true
        sticky: true
        importance: high
        tag: 3d-printer
        image: /api/camera_proxy/camera.octoprint
        clickAction: /lovelace/3d-printer
  mode: single
- id: '1720001919454'
  alias: Bambu Lab P1S - Status
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.bambu_lab_p1s_print_progress
    - sensor.bambu_lab_p1s_task_name
  condition:
  - condition: not
    conditions:
    - condition: state
      entity_id: sensor.bambu_lab_p1s_print_progress
      state: unknown
  action:
  - service: notify.mobile_app_pixel_7
    data:
      title: "{% if is_state('sensor.bambu_lab_p1s_task_name', 'unavailable') %}\n
        \ Bambu Lab P1S\n{% else %}\n  {% if has_value('sensor.bambu_lab_p1s_print_progress')
        %}{{states('sensor.bambu_lab_p1s_print_progress')}}% - {% endif %}{{states('sensor.bambu_lab_p1s_task_name')
        | title}}\n{% endif %}"
      message: "{% if is_state('sensor.bambu_lab_p1s_task_name', 'unavailable') %}\n
        \ {{states('bambu_lab_p1s_current_stage') | title}}\n{% else %}\n  {{states('sensor.bambu_lab_p1s_current_stage')
        | title}}\n  ETA: {{ int(as_timestamp(now()) + int(states('sensor.bambu_lab_p1s_remaining_time'))*60)
        | timestamp_custom('%H:%M', true) }}\n{% endif %}"
      data:
        channel: 3D Printer
        persistent: true
        sticky: true
        importance: medium
        tag: 3d-printer
        image: /api/camera_proxy/camera.octoprint
        clickAction: /lovelace/3d-printer
    alias: Notify Status
  mode: single
- id: '1721144982237'
  alias: Person Detected
  description: ''
  trigger:
  - type: turned_on
    platform: device
    device_id: 4998f70dee450c2aedc4987454e7bdc0
    entity_id: 32afedc40f7c62baf83e708a0e927a3f
    domain: binary_sensor
  condition: []
  action:
  - service: notify.mobile_app_pixel_7
    data:
      message: Person detected
      data:
        importance: high
        tag: person-detected
        image: /api/camera_proxy/camera.doorbell
  mode: single
