- id: '1550001835411'
  alias: 'The Button #1, 1 click'
  description: Gang
  trigger:
  - event_data:
      entity_id: zwave.fibaro_button_1
      scene_data: 7680
      scene_id: 1
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - data:
      desired_state: toggle
    service: script.garasjeport
- id: '1550606425406'
  alias: Keyfob Car, Square
  trigger:
  - event_data:
      entity_id: zwave.fibaro_keyfob_carkey
      scene_data: 7680
      scene_id: 1
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - data:
      desired_state: toggle
    service: script.garasjeport
- id: '1551629601000'
  alias: Keyfob Car, Cross
  trigger:
  - event_data:
      entity_id: zwave.fibaro_keyfob_carkey
      scene_data: 7680
      scene_id: 3
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - data:
      entity_id: lock.hoveddor
    service: lock.unlock
- id: '155821217700'
  alias: Kjeller Bod Enter
  trigger:
  - entity_id: sensor.kjeller_bod_motion
    from: '0'
    platform: state
    to: '8'
  action:
  - data:
      entity_id: scene.kjeller_bod_pa
    service: scene.turn_on
- id: '155821217701'
  alias: Kjeller Bod Exit
  trigger:
  - entity_id: sensor.kjeller_bod_motion
    for: 00:15
    from: '8'
    platform: state
    to: '0'
  condition:
  - condition: state
    entity_id: binary_sensor.octoprint_printing
    state: 'off'
  action:
  - data:
      entity_id: scene.kjeller_bod_av
    service: scene.turn_on
  mode: single
- id: '1551651260765'
  alias: Motion Gang
  trigger:
  - entity_id: sensor.gang_motion
    from: '0'
    platform: state
    to: '8'
  condition:
  - condition: state
    entity_id: switch.yttergang
    state: 'off'
  - after: 06:00
    before: '21:00'
    condition: time
  action:
  - data:
      entity_id: scene.gang_pa
    service: scene.turn_on
  mode: single
- id: '1554639006348'
  alias: 'The Button #2, 1 click'
  trigger:
  - event_data:
      entity_id: zwave.fibaro_button_2
      scene_data: 7680
      scene_id: 1
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - data:
      entity_id: lock.hoveddor
    service: lock.unlock
- id: '1572437961272'
  alias: Varme, Lav når borte eller kveld
  description: ''
  trigger:
  - at: '22:00'
    platform: time
  - entity_id: group.all_persons
    for: 00:30
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - service: script.lav_varme
- id: '1572438496325'
  alias: Varme, Høy når hjemme
  description: ''
  trigger:
  - entity_id: group.all_persons
    from: not_home
    platform: state
    to: home
  condition:
  - before: '22:00'
    condition: time
  action:
  - service: script.hoy_varme
- id: '1572894057692'
  alias: Varme, Høy på morgen i helg
  description: ''
  trigger:
  - at: 08:00
    platform: time
  condition:
  - condition: state
    entity_id: group.all_persons
    state: home
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'off'
  action:
  - service: script.hoy_varme
- id: '1583994012421'
  alias: Varme, Høy på morgen ukedager
  description: ''
  trigger:
  - at: 06:00
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  - condition: state
    entity_id: group.all_persons
    state: home
  action:
  - data: {}
    service: script.hoy_varme
- id: '1586514634514'
  alias: Lås dører når ingen hjemme
  description: ''
  trigger:
  - entity_id: group.all_persons
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - data: {}
    entity_id: lock.hoveddor
    service: lock.lock
  - data: {}
    entity_id: lock.boddor
    service: lock.lock
- id: '1587456032987'
  alias: Garderobelys Svakt
  description: ''
  trigger:
  - entity_id: light.soverom_seng
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      brightness: 12
      transition: 3
    entity_id:
    - light.garderobe_stine
    - light.garderobe_torkild
    service: light.turn_on
- id: '1587456195101'
  alias: Garderobelys Kraftig
  description: ''
  trigger:
  - entity_id: light.soverom_seng
    from: 'off'
    platform: state
  condition: []
  action:
  - data:
      brightness: 255
      transition: 3
    entity_id:
    - light.garderobe_stine
    - light.garderobe_torkild
    service: light.turn_on
  mode: single
- id: '1600502553956'
  alias: Tag Hoveddør is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 749bf980-aed0-476c-8156-ae3e53dbb8aa
  condition: []
  action:
  - service: lock.unlock
    data: {}
    entity_id: lock.hoveddor
  mode: single
- id: '1607377536167'
  alias: Octoprint Start
  description: ''
  trigger:
  - entity_id: binary_sensor.octoprint_printing
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: scene.kjeller_bod_pa
    service: scene.turn_on
  mode: single
- id: '1617095260219'
  alias: Plantelampe På
  description: ''
  trigger:
  - platform: time
    at: 08:00
  condition: []
  action:
  - type: turn_on
    device_id: 924d4e04e1d4430ebf27dc71e456d864
    entity_id: switch.plantelampe
    domain: switch
  mode: single
- id: '1617095288500'
  alias: Plantelampe Av
  description: ''
  trigger:
  - platform: time
    at: '20:00'
  condition: []
  action:
  - type: turn_off
    device_id: 924d4e04e1d4430ebf27dc71e456d864
    entity_id: switch.plantelampe
    domain: switch
  mode: single
- id: '1625740809871'
  alias: Garasjelys på
  description: ''
  trigger:
  - platform: device
    device_id: 48be7c045b27f5f27f6e40300f660060
    domain: cover
    entity_id: cover.garage_door
    type: opening
  - platform: device
    device_id: 48be7c045b27f5f27f6e40300f660060
    domain: cover
    entity_id: cover.garage_door
    type: opened
  condition: []
  action:
  - service: light.turn_on
    target:
      entity_id: light.garasjelys
  mode: single
- id: '1625740885485'
  alias: Garasjelys av
  description: ''
  trigger:
  - platform: device
    device_id: 48be7c045b27f5f27f6e40300f660060
    domain: cover
    entity_id: cover.garage_door
    type: closed
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id: light.garasjelys
  mode: single
