- id: '1549872178100'
  alias: 'Hue Tap Uno #2'
  trigger:
  - event_data:
      event: 16
      id: hue_tap_uno
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - data:
      entity_id: light.stue_vegg_level
    service: light.turn_on
- id: '1549907898507'
  alias: 'Hue Tap Uno #1'
  trigger:
  - event_data:
      event: 34
      id: hue_tap_uno
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - data:
      entity_id: light.stue_vegg_level
    service: light.turn_off
