homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret altitude
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam

  customize: !include customize.yaml

  # auth is done in reverse proxy
  auth_providers:
    - type: trusted_networks
      trusted_networks:
      - 0.0.0.0/0

default_config:

frontend:

system_health:

mqtt:
  username: homeassistant
  password: !secret mqtt_password

influxdb:

recorder:
  purge_interval: 1
  purge_keep_days: 14

zwave:
  usb_path: /dev/serial/by-id/usb-0658_0200-if00
  network_key: !secret zwave_key
  device_config: !include zwave_device_config.yaml
  device_config_glob: !include zwave_device_config_glob.yaml

neato:
  username: !secret neato_user
  password: !secret neato_pass

verisure:
  username: !secret verisure_user
  password: !secret verisure_pass

emulated_hue:
  listen_port: 8300
  expose_by_default: false

notify:
  - platform: html5
    name: web
    vapid_email: !secret vapid_email
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key

media_player:
  - platform: samsungtv
    host: !secret samsungtv_ip
    port: 8001

tibber:
  access_token: !secret tibber_token


# Enables configuration UI
config:

http:
  use_x_forwarded_for: true
  trusted_proxies: 172.18.0.0/24

updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

sensor: !include sensors.yaml

weather:
  - platform: met

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

group: !include groups.yaml
automation: !include automations.yaml
scene: !include scene.yaml
plant: !include plants.yaml
script: !include scripts.yaml

#input_text:
#  display_text:
#    name: Text
#
#input_select:
#  display_mode:
#    options:
#      - Text
#      - Date
#
#input_boolean:
#  display_time:
#    name: Show Time
#
