homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret altitude
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml

  auth_providers:
    - type: homeassistant

default_config:

frontend:

system_health:

influxdb:

recorder:
  purge_keep_days: 7

emulated_hue:
  listen_port: 8300
  expose_by_default: false

notify:
  - platform: html5
    name: web
    vapid_email: !secret vapid_email
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key

config:

http:
  use_x_forwarded_for: true
  trusted_proxies: 172.18.0.0/24

discovery:

conversation:

history:

logbook:

sun:

tts:
  - platform: google_translate
    service_name: google_say

group: !include groups.yaml
automation: !include automations.yaml
scene: !include scenes.yaml
scene old: !include scenes_old.yaml
plant: !include plants.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
mqtt: !include mqtt.yaml
binary_sensor: !include binary_sensor.yaml
light: !include lights.yaml

