homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret altitude
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml

  # auth is done in reverse proxy
  auth_providers:
    - type: trusted_networks
      trusted_networks:
      - 0.0.0.0/0

default_config:

frontend:

lovelace:
  mode: yaml

system_health:

mqtt:
  username: homeassistant
  password: !secret mqtt_password

influxdb:

recorder:
  purge_interval: 1
  purge_keep_days: 14

zwave:
  usb_path: /dev/serial/by-id/usb-0658_0200-if00
  network_key: !secret zwave_key
  device_config: !include zwave_device_config.yaml
  device_config_glob: !include zwave_device_config_glob.yaml

neato:
  username: !secret neato_user
  password: !secret neato_pass

verisure:
  username: !secret verisure_user
  password: !secret verisure_pass
  default_lock_code: !secret verisure_pin
  code_digits: 6

emulated_hue:
  listen_port: 8300
  expose_by_default: false

notify:
  - platform: html5
    name: web
    vapid_email: !secret vapid_email
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key

media_player:
  - platform: samsungtv
    host: !secret samsungtv_ip
    mac: !secret samsungtv_mac
    port: 8001

tibber:
  access_token: !secret tibber_token


config:

http:
  use_x_forwarded_for: true
  trusted_proxies: 172.18.0.0/24

updater:

  discovery:

conversation:

history:

logbook:

sun:

tts:
  - platform: google_translate
    service_name: google_say

google:
  client_id: !secret google_cal_client_id
  client_secret: !secret google_cal_secret

speedtestdotnet:
  scan_interval: '02:00:00'

group: !include groups.yaml
automation: !include automations.yaml
scene: !include scene.yaml
plant: !include plants.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensor.yaml
lock: !include locks.yaml
