- platform: template
  covers:
    garasjeport:
      friendly_name: Garasjeport
      device_class: garage
      value_template: "{{ is_state('binary_sensor.garasjeport', 'on') }}"
      open_cover:
        service: script.garasjeport
        data:
          desired_state: open
      close_cover:
        service: script.garasjeport
        data:
          desired_state: closed
