
default_view:
  view: yes
  icon: mdi:home 
  entities:
    - updater.updater
    - group.scener
    - group.spisestua
    - group.soverommet
    - group.gjesterommet
    - group.gangen
    - group.stua
    - group.kjokken
    - group.scener
    - scene.pa
    - scene.helt_av
    - scene.natta
    - group.display
sensors:
  view: yes
  icon: mdi:speedometer
  entities:
    - group.power_sensors
    - group.energy_sensors

media:
  view: yes
  icon: mdi:projector-screen
  entities:
    - media_player.samsung_tv_remote
    - media_player.stua
    - media_player.shield_android_tvt 

stove:
  view: yes
  icon: mdi:broom
  entities:
    - sensor.stve_battery
    - sensor.stve_status
    - switch.stve_clean
    - switch.stve_schedule
    - camera.stve_cleaning_map

plants:
  view: yes
  icon: mdi:flower
  entities:
    - plant.cayenne
    - plant.jalapeno
    - plant.thai
    - plant.habanero

automation:
  view: yes
  icon: mdi:robot
  entities:
    - group.all_automations

spisestua:
  name: Spisestua
  entities:
    - light.nuppelampa
    - light.spisestua_level
    - switch.vitrineskapet_switch

stua:
  name: Stua
  entities:
    - light.stua_level
    - switch.vinduet_switch

kjokken:
  name: Kjøkken
  entities:
    - light.kjokken_level

gangen:
  name: Gangen
  entities:
    - switch.gangen_switch

soverommet:
  name: Soverommet
  entities:
    - light.soverommet

gjesterommet:
  name: Gjesterommet
  entities:
    - light.gjesterommet
    - switch.plantelampa_switch

power_sensors:
  name: Effekt
  entities:
    - sensor.gangen_power
    - sensor.kjokken_power
    - sensor.stua_power
    - sensor.spisestua_power
    - sensor.plantelampa_power

energy_sensors:
  name: Forbruk
  entities:
    - sensor.gangen_energy
    - sensor.kjokken_energy
    - sensor.stua_energy
    - sensor.spisestua_energy
    - sensor.plantelampa_energy

display:
  name: Display
  entities:
    - input_select.display_mode
    - input_text.display_text

