- platform: template
  name: Garasjeport
  value_template: "{{ is_state('binary_sensor.garasjeport', 'off') }}"
  lock:
    service: script.garasjeport
    data:
      desired_state: closed
  unlock:
    service: script.garasjeport
    data:
      desired_state: open
