- platform: time_date
  display_options:
    - "time"
    - "date"
- platform: mqtt
  name: "Kjeller Temperatur"
  state_topic: "humidity/basement"
  unit_of_measurement: "°C"
  value_template: "{{ value_json.temperature }}"
- platform: mqtt
  name: "Kjeller Luftfuktighet"
  state_topic: "humidity/basement"
  unit_of_measurement: "%"
  value_template: "{{ value_json.humidity }}"
  device_class: humidity
