- platform: time_date
  display_options:
    - 'time'
    - 'date'
- platform: template
  sensors:
    wind_strength_mps:
      value_template: "{{ (states('sensor.netatmo_wind_strength') | float / 3.6) | round(1) }}"
      unit_of_measurement: "m/s"
    date_short:
      value_template: "{{ strptime(states('sensor.date'), '%Y-%m-%d').strftime('%-d %b') }}"
- platform: miflora
  name: 'flower1_spathiphyllum'
  mac: 'C4:7C:8D:66:2D:BC'
  force_update: true
- platform: miflora
  name: 'flower2_palme'
  mac: 'C4:7C:8D:66:29:3E'
  force_update: true
- platform: miflora
  name: 'flower3_monstera'
  mac: 'C4:7C:8D:66:2C:14'
  force_update: true
- platform: miflora
  name: 'flower4_ginseng'
  mac: 'C4:7C:8D:66:25:C9'
  force_update: true
- platform: miflora
  name: 'flower5_mynte'
  mac: '80:EA:CA:88:D7:D9'
  force_update: true
- platform: miflora
  name: 'flower6_drageblod_trapp'
  mac: '80:EA:CA:88:D8:D0'
  force_update: true
- platform: miflora
  name: 'flower7_drageblod_kjokken'
  mac: '80:EA:CA:88:D7:61'
  force_update: true
- platform: miflora
  name: 'flower8_kontor'
  mac: '80:EA:CA:88:D8:0D'
  force_update: true
