title: Home
views:
  - badges:
      - sensor.netatmo_indoor_temperature
      - sensor.gang_temperature
      - sensor.kjeller_bod_temperature
      - lock.hoveddor
      - binary_sensor.garasjeport
    title: Home
    cards:
      - entities:
          - entity: switch.gang_oppe
          - entity: light.gang_nede
          - entity: switch.yttergang
        title: Gang
        type: entities
      - entities:
          - entity: light.stue_vegg
        title: Stue
        type: entities
      - entities:
          - entity: light.kjeller_tak
          - entity: light.kjeller_vegg
          - entity: switch.kjeller_bod
          - entity: switch.arbeidsbenk
        title: Kjeller
        type: entities
      - entities:
          - entity: switch.treningsrom_tak
          - entity: switch.treningsrom_spot
        title: Andre Etasje
        type: entities
      - entities:
          - entity: media_player.kitchen
          - entity: media_player.livingroom
          - entity: media_player.bedroom
        show_header_toggle: false
        title: Sonos
        type: entities
      - type: vertical-stack
        cards:
          - type: conditional
            conditions:
              - entity: binary_sensor.garasjeport
                state: 'off'
            card:
              type: entities
              title: Garasjeport
              show_header_toggle: false
              entities:
                - entity: binary_sensor.garasjeport
                - entity: script.garasje_apne
          - type: conditional
            conditions:
              - entity: binary_sensor.garasjeport
                state: 'on'
            card:
              type: entities
              title: Garasjeport
              show_header_toggle: false
              entities:
                - entity: binary_sensor.garasjeport
                - entity: script.garasje_lukk
      - type: entities
        title: Terrasse
        entities:
          - entity: switch.terrassevarmer
          - entity: sensor.terrassevarmer_power
        show_header_toggle: false
  - title: Strøm
    cards:
      - type: sensor
        entity: sensor.electricity_price_home
        graph: line
        detail: 2
