title: Villa GT
resources:
  - url: /local/atomic_calendar.js
    type: module
views:
- title: Home
  cards:
    - type: entities
      entities:
        - entity: switch.gang_oppe
        - entity: light.gang_nede
        - entity: switch.yttergang
      title: Gang
    - type: entities
      entities:
        - entity: light.stue_vegg
      title: Stue
    - type: entities
      entities:
        - entity: light.kjeller_tak
        - entity: light.kjeller_vegg
        - entity: switch.kjeller_bod
        - entity: switch.arbeidsbenk
      title: Kjeller
    - type: entities
      entities:
        - entity: switch.treningsrom_tak
        - entity: switch.treningsrom_spot
      title: Andre Etasje
    - type: entities
      title: Hus
      show_header_toggle: false
      entities:
        - lock.hoveddor
        - lock.boddor
        - lock.garasjeport
        - switch.terrassevarmer
    - type: glance
      entities:
      - sensor.netatmo_outdoor_temperature
      - sensor.netatmo_indoor_temperature
      - sensor.gang_temperature
      - sensor.kjeller_bod_temperature
      - sensor.real_time_consumption
- title: Calendar
  panel: true
  cards:
    - type: "custom:atomic-calendar"
      title: "Calendar"
      enableModeChange: true
      defaultMode: 1
      entities:
      - entity: calendar.gt
        color: red
        type: icon2
- title: Media
  cards:
    - type: entities
      title: Sonos
      entities:
        - entity: media_player.kitchen
        - entity: media_player.livingroom
        - entity: media_player.bedroom
      show_header_toggle: false
    - type: media-control
      entity: media_player.sound_bar
