title: Villa GT
resources:
  - url: /local/atomic_calendar.js
    type: module
views:
- title: Hjem
  cards:
    - type: glance
      entities:
        - entity: sensor.netatmo_outdoor_temperature
        - entity: sensor.netatmo_indoor_temperature
        - entity: sensor.netatmo_rain_sum_1
        - entity: sensor.wind_strength_mps
        - entity: sensor.real_time_consumption
    - type: entities
      entities:
        - entity: switch.gang_oppe
        - entity: light.gang_nede
        - entity: switch.yttergang
      title: Gang
    - type: entities
      title: Første Etasje
      entities:
        - entity: light.stue_spot
        - entity: light.stuelampe
        - entity: light.kontor_spot
        - entity: light.nuppelampa
    - type: entities
      entities:
        - entity: light.kjeller_tak
        - entity: light.kjeller_vegg
        - entity: switch.kjeller_bod
        - entity: switch.arbeidsbenk
      title: Kjeller
    - type: entities
      entities:
        - entity: light.soverom_seng
        - entity: switch.treningsrom_tak
        - entity: switch.treningsrom_spot
      title: Andre Etasje
    - type: entities
      title: Hus
      show_header_toggle: false
      entities:
        - lock.garasjeport
        - switch.garasjelys
        - lock.hoveddor
        - lock.boddor
        - switch.terrassevarmer
- title: Klima
  cards:
    - type: entities
      title: Vindu
      entities:
        - cover.stue
        - cover.kjokken
        - cover.kontor
    - type: entities
      title: Varme
      entities:
        - script.hoy_varme
        - script.lav_varme
        - climate.stue
        - climate.kontor
        - climate.treningsrom
        - climate.barnerom
- title: Kalender
  panel: true
  cards:
    - type: "custom:atomic-calendar"
      title: "Calendar"
      enableModeChange: true
      defaultMode: 1
      entities:
      - entity: calendar.gt
        color: red
        type: icon2
- title: Media
  cards:
    - type: entities
      title: Sonos
      entities:
        - entity: media_player.kitchen
        - entity: media_player.livingroom
        - entity: media_player.bedroom
      show_header_toggle: false
    - type: media-control
      entity: media_player.sound_bar
