title: home

views:
  - title: Main
    id: main
    cards:
      - id: 606a3b956ee443b0a91429145c9c67eb  # Automatically created id
        type: horizontal-stack
        cards:
          - type: gauge
            title: Cayenne
            entity: sensor.cayenne_moisture
            unit: '%'
            graph: line
            severity:
              green: 50
              yellow: 30
              red: 0
          - type: gauge
            title: Habanero
            entity: sensor.habanero_moisture
            unit: '%'
            graph: line
            severity:
              green: 50
              yellow: 30
              red: 0
          - type: gauge
            title: Jalapeño
            entity: sensor.jalapeno_moisture
            unit: '%'
            graph: line
            severity:
              green: 50
              yellow: 30
              red: 0
          - type: gauge
            title: Thai Chili
            entity: sensor.thai_moisture
            unit: '%'
            graph: line
            severity:
              green: 50
              yellow: 30
              red: 0
