title: Villa GT
views:
- title: Home
  badges:
      - sensor.netatmo_outdoor_temperature
      - sensor.netatmo_indoor_temperature
      - sensor.gang_temperature
      - sensor.kjeller_bod_temperature
  cards:
    - entities:
        - entity: switch.gang_oppe
        - entity: light.gang_nede
        - entity: switch.yttergang
      title: Gang
      type: entities
    - entities:
        - entity: light.stue_vegg
      title: Stue
      type: entities
    - entities:
        - entity: light.kjeller_tak
        - entity: light.kjeller_vegg
        - entity: switch.kjeller_bod
        - entity: switch.arbeidsbenk
      title: Kjeller
      type: entities
    - entities:
        - entity: switch.treningsrom_tak
        - entity: switch.treningsrom_spot
      title: Andre Etasje
      type: entities
    - type: vertical-stack
      cards:
        - type: conditional
          conditions:
            - entity: binary_sensor.garasjeport
              state: 'off'
          card:
            type: entities
            title: Garasjeport
            show_header_toggle: false
            entities:
              - entity: binary_sensor.garasjeport
              - entity: script.garasje_apne
        - type: conditional
          conditions:
            - entity: binary_sensor.garasjeport
              state: 'on'
          card:
            type: entities
            title: Garasjeport
            show_header_toggle: false
            entities:
              - entity: binary_sensor.garasjeport
              - entity: script.garasje_lukk
    - type: entities
      title: Hus
      show_header_toggle: false
      entities:
        - lock.hoveddor
        - lock.boddor
        - sensor.real_time_consumption
        - sensor.electricity_price_home
    - type: entities
      title: Ute
      show_header_toggle: false
      entities:
        - switch.terrassevarmer
        - sensor.terrassevarmer_power
- title: Media
  cards:
    - type: entities
      title: Sonos
      entities:
        - entity: media_player.kitchen
        - entity: media_player.livingroom
        - entity: media_player.bedroom
      show_header_toggle: false
    - type: media-control
      entity: media_player.sound_bar
