sensor.gangen_alarm_level:
  ignored: true
  polling_intensity: 0
sensor.gangen_alarm_type:
  ignored: true
  polling_intensity: 0
sensor.gangen_exporting:
  ignored: true
  polling_intensity: 0
sensor.gangen_heat:
  ignored: true
  polling_intensity: 0
sensor.gangen_power_management:
  ignored: true
  polling_intensity: 0
sensor.gangen_sourcenodeid:
  ignored: true
  polling_intensity: 0
sensor.kjokken_alarm_level:
  ignored: true
  polling_intensity: 0
sensor.kjokken_alarm_type:
  ignored: true
  polling_intensity: 0
sensor.kjokken_exporting:
  ignored: true
  polling_intensity: 0
sensor.kjokken_heat:
  ignored: true
  polling_intensity: 0
sensor.kjokken_power_management:
  ignored: true
  polling_intensity: 0
sensor.kjokken_sourcenodeid:
  ignored: true
  polling_intensity: 0
sensor.kjokken_system:
  ignored: true
  polling_intensity: 0
sensor.spisestua_alarm_level:
  ignored: true
  polling_intensity: 0
sensor.spisestua_alarm_type:
  ignored: true
  polling_intensity: 0
sensor.spisestua_exporting:
  ignored: true
  polling_intensity: 0
sensor.spisestua_heat:
  ignored: true
  polling_intensity: 0
sensor.spisestua_power_management:
  ignored: true
  polling_intensity: 0
sensor.spisestua_sourcenodeid:
  ignored: true
  polling_intensity: 0
sensor.spisestua_system:
  ignored: true
  polling_intensity: 0
sensor.stua_alarm_level:
  ignored: true
  polling_intensity: 0
sensor.stua_alarm_type:
  ignored: true
  polling_intensity: 0
sensor.stua_exporting:
  ignored: true
  polling_intensity: 0
sensor.stua_heat:
  ignored: true
  polling_intensity: 0
sensor.stua_power_management:
  ignored: true
  polling_intensity: 0
sensor.stua_sourcenodeid:
  ignored: true
  polling_intensity: 0
sensor.stua_system:
  ignored: true
  polling_intensity: 0
