"*_alarm_level":
  ignored: true
"*_alarm_type":
  ignored: true
"*_exporting":
  ignored: true
"*_heat":
  ignored: true
"*_power_management":
  ignored: true
"*_sourcenodeid":
  ignored: true
"sensor.*_system":
  ignored: true
"sensor.*_power_2":
  ignored: true
"switch.*_switch_2":
  ignored: true
"light.*_level_2":
  ignored: true

