esphome:
  name: node1
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: "Rosmarin"
  password: "beateerenkosepus"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Node1 Fallback Hotspot"
    password: "8llFAVHcvroq"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "8FCrJct4tHrwv6KuLHBe"

ota:
  password: "8FCrJct4tHrwv6KuLHBe"
  
sensor:
- platform: dht
  pin: GPIO23
  model: DHT11
  temperature:
    name: "Node1 Temperature"
  humidity:
    name: "Node1 Humidity"
  update_interval: 60s
